### ISSUE TITLE
Don't build-depend on bindgen?

### ISSUE THREAD

**Issue by vberger** [rusty-desktop/input.rs#2]
It makes clang a build-dependency, which is rather painful. Is there a real gain compared to checking in git the output of bindgen?

**Comment by Drakulix** [comment]
I wanted to have a fully integrated build process. I tend to find rebuilding the bindings on build to be good practice, as updates of bindgen and the header file are updating the generated bindings immediately.

That's also the main motivation for having input-sys, as rebuilding input, should not always require a rebuild of input. But that still does not remove the libclang dependency, whats you motivation to get rid of it? CI?

**Comment by vberger** [comment]
Well, right before opening this Issues, I tried to compile smithay on my laptop after merging your libinput backend, and it failed because I hadn't clang installed.

Being on gentoo, building clang took me around 3/4 of an hour :D

But mostly, this means that building smithay requires clang. It's not that bad, but that's one more dependency cargo has no control over. I tend to prefer trying to reduce them to a minimum, that's all.

**Comment by Drakulix** [comment]
I am trying to think of a good way to circumvent this for crates.io releases, where a fixed gen.rs would not be a big deal at all, while still preserving this behavior for local debug builds and maybe for travis to know, when my gen.rs is out of date.

If you have some suggestions, now is the time ;)

**Comment by Drakulix** [comment]
This will be fixed by #3 once merged and then published as 0.2.
bindgen is now only used by an optional feature and travis should check for an up-to-date gen.rs file.

**Comment by vberger** [comment]
Sounds like a nice solution, thanks! 👍
